#!/bin/bash

#Generate URDF from Xacro files
#rosrun xacro xacro.py ./urdf/darci.urdf.xacro > ./urdf/darci.urdf

#Convert URDF to SDF
gzsdf print ./urdf/autobed.URDF > sdf/model.sdf

#Fix Links as generated by the gzsdf command
sed -i "s/hrl_gazebo_autobed\/urdf/autobed/g" sdf/model.sdf
