#!/bin/bash

#Generate URDF from Xacro files
#rosrun xacro xacro.py ./urdf/darci.urdf.xacro > ./urdf/darci.urdf

#Convert URDF to SDF
gzsdf print ./urdf/autobed.URDF > sdf/model.sdf
#Add ability to add plugins to the sdf
sed -i "s/<\/model>/  <plugin name='ros_model_plugin' filename='libros_model_plugin.so'\/>\\
  <\/model>/1" sdf/model.sdf

#Fix Links as generated by the gzsdf command
sed -i "s/hrl_gazebo_autobed\/urdf/autobed/g" sdf/model.sdf

#Copy new file into desired locations
rm ~/.gazebo/models/autobed/model.sdf
cp sdf/model.sdf ~/.gazebo/models/autobed/

