#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install build-essential python-dev python-pip
sudo pip install --upgrade tornado

mkdir -p ~/Autobed
cd ~/Autobed

if [ ! -d "./hrl_autobed_dev" ]
then
	echo "[Autobed Install] Retrieving Autobed Software"
	git clone https://github.com/gt-ros-pkg/hrl_autobed_dev.git
else
	echo "[Autobed Install] Autobed Software Found. Updating."
	cd ./hrl_autobed_dev
	git pull
	cd ../
fi

# Add autobed_server to startup on rc.local
AUTOBED_SERVER="/home/$USER/Autobed/hrl_autobed_dev/web_only/autobed_server.py"
if grep -q "$AUTOBED_SERVER" /etc/rc.local
then
    echo "[Autobed Install] Autobed Server already set to start on boot"
else
    echo "[Autobed Install] Setting Autobed Server to start on boot"
    sudo cp /etc/rc.local /etc/rc.local.bak
    sudo sed --in-place "/^exit 0/i $AUTOBED_SERVER >> /var/log/autobed.log 2>1&\n" /etc/rc.local
fi

if which apache2
then
	echo "[Autobed Install] Apache Web Server Already Installed"
else
	echo "[Autobed Install] Installing Apache Web Server"
	sudo apt-get install apache2
fi

sudo sh -c "sed \"s/ABD-USER/$USER/g\" /home/$USER/Autobed/hrl_autobed_dev/web_only/autobed_site_config >> /etc/apache2/sites-available/autobed"
sudo a2ensite autobed
sudo a2dissite default
sudo service apache2 reload

echo "[Autobed Install] Install Complete"
