#!/usr/bin/bash

mkdir -p ~/git
cd ~/git
git clone https://github.com/gt-ros-pkg/hrl_autobed_dev.git --branch web-only

echo "[Autobed Install] Installing PIGPIO daemon"
# From http://abyz.co.uk/rpi/pigpio/download.html
wget abyz.co.uk/rpi/pigpio/pigpio.zip
unzip pigpio.zip
cd PIGPIO
make
make install

# Add pigpiod to startup on rc.local
if grep -q "/usr/local/bin/pigpiod"
    echo "[Autobed Install] PIGPIO already set to start on boot"
else
    echo "[Autobed Install] Setting PIGPIO daemon to start on boot"
    sudo cp /etc/rc.local /etc/rc.local.bak
    sudo sed --in-place "/^exit 0/i sudo /usr/local/bin/pigpiod \n" /etc/rc.local
fi

echo "[Autobed Install] Installing Apache Web Server"
sudo apt-get install apache2
a2enmod cgid
sudo cp ./hrl_autobed_dev/web_only/autobed_site_config /etc/apache2/sites-available/autobed
sudo a2ensite autobed

echo "[Autobed Install] Install Completed -- Please reboot"
